apiVersion: 1

datasources:
  # Prometheus - Spring Boot Actuator 메트릭
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "1s"

  # Loki - 로그 수집
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
