apiVersion: 1

datasources:
  # InfluxDB - k6 부하 테스트 메트릭
  - name: InfluxDB-k6
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    isDefault: true
    editable: true

  # Prometheus - Spring Boot 애플리케이션 메트릭
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: true
